---
- hosts: controller 
  tasks:
    - name: install software-properties-common
      apt: name=software-properties-common state=present 

    - name: Add repositories
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main' filename=cloudarchive-mitaka.list state=present

    - name: update&upgrade
      apt:
        update_cache: yes
        upgrade: dist
      tags: sekhar

#    - name: pythan-openstackclient
 #     apt: name=python-openstackclient state=present
  #    tags: hello
